### ISSUE TITLE
Incompatible with Edge public release

### ISSUE THREAD

**Issue by Finetuned** [MicrosoftEdge/WebView2Samples#12]
Edge has just been publicly released. After uninstalling canary, the sample fails with :

```Loader skipped an incompatible version: C:\Program Files (x86)\Microsoft\Edge\Application\79.0.309.65```

**Comment by OmarJay1** [comment]
I think it's a version issue. 
https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes

I did try to install the latest WebView2 version that would support 79.0.309.65, which I believe is 0.8.270.  Building gave lots of errors, for instance:
WebView2Samples\WebView2APISample\AppWindow.h(26,22): error C2143: syntax error: missing ';' before '*'

**Comment by pagoe-msft** [comment]
Hi Finetuned,

Yes, this is a version issue.

Checkout my response here: https://github.com/MicrosoftEdge/WebViewFeedback/issues/103

**Comment by pagoe-msft** [comment]
Hi OmarJay1,

We update our sample app to always use the latest SDK. As of this writing, the latest version of our SDK is 0.8.355 (https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/releasenotes#08355)

Moving back to previous SDK's won't work because the Sample App is built around the newest APIs.

**Comment by OmarJay1** [comment]
Hi pagoe-msft, thank you.  

Is there any way to release an app that uses WebView2 and targets the production release of Edge? 0.8.270. will not build, at lease with the samples.  0.8.355 doesn't work with the stable release of Edge.

The Browser example works for Edge 79.0.309.65,  but that doesn't seem to expose any interface.  

It's not such a big issue right now because users have to go out of their way to download the new Edge anyway.  It would be nice if the next Windows update that includes Edge would have a version that works with the WebView2 Interface.  

I understand that it takes time to make sure security is solid, but it would be nice to have a rough estimate on when a production app that uses WebView2 can be released.  

Thanks.

**Comment by pagoe-msft** [comment]
Hi Omarjay1,

That's great feedback for us! The first Sample App we released works on 0.8.314. When the stable version of Edge catches up, we will release instructions on how you can checkout the API Sample that is in line with the stable version of Edge.
